delete from user;
delete from movie;
delete from metadata_tmdb;
delete from role;
INSERT INTO `user` VALUES  (1,'badadmin','ssecrett','Bad','Admin',TRUE,FALSE,'2018-01-01');
INSERT INTO `user` VALUES  (2,'jfourieadmin','ssecrett','Jacques','Fourie',TRUE,TRUE,'2018-01-02');
INSERT INTO `user` VALUES  (3,'jfourie','ssecrett','Jacques','Fourie',FALSE,TRUE,'2018-01-02');
INSERT INTO `user` VALUES  (4,'lfoxy','ssecrett','Lucy','Foxy',FALSE,TRUE,'2018-02-10');
INSERT INTO `user` VALUES  (5,'baduser','ssecrett','Bad','User',FALSE,FALSE,'2018-02-10');
INSERT INTO `user` VALUES  (6,'pwaite','ssecrett','Paula','Waite',FALSE,TRUE,'2018-03-15');
INSERT INTO `user` VALUES  (7,'pwaiteadmin','ssecrett','Paula','Waite',TRUE,TRUE,'2018-03-15');
INSERT INTO `movie` VALUES (1,'Jack Reacher', '38bmEXmuJuInLs9dwfgOGCHmZ7l.jpg','test','test','test',5,'jackreacher','jfourie',3);
INSERT INTO `movie` VALUES (2,'War Games', 'rQocmooj7bFKS2vZfzWBB5O12eR.jpg','test','test','test',5,'wargames','jfourie',3);
INSERT INTO `movie` VALUES (3,'Blade Runner 2048', 'gajva2L0rPYkEWjzgFlBXCAVBE5.jpg','test','test','test',3,'bladerunner2048','jfourie',3);
INSERT INTO `movie` VALUES (4,'Blade Runner', 'p64TtbZGCElxQHpAMWmDHkWJlH2.jpg','test','test','test',3,'bladerunner','lfoxy',4);
INSERT INTO `movie` VALUES (5,'Abyss', 'kRP5dGXDhKt7bDpXX4YBa4dRwlL.jpg','test','test','test',3,'abyss','lfoxy',4);
INSERT INTO `movie` VALUES (6,'The Accountant', 'afhAUuWVB7k7PjJUd4lwO3rzhSq.jpg','test','test','test',4,'accountant','lfoxy',4);
INSERT INTO `movie` VALUES (7,'Atomic Blonde', 'kV9R5h0Yct1kR8Hf8sJ1nX0Vz4x.jpg','test','test','test',3,'atomicblonde','lfoxy',4);
INSERT INTO `movie` VALUES (8,'Ultimate Avengers', 'we6igIU5gXVwuSL6M6pJP75TwEf.jpg','test','test','test',3,'ultimateavengers','lfoxy',4);
INSERT INTO `movie` VALUES (9,'After Earth', 'd0vReo0jcMhBjCLYZAFqWHcb7Lj.jpg','test','test','test',3,'afterearth','lfoxy',4);
INSERT INTO `movie` VALUES (10,'Blade', 'r0RQ9ZOEZglLOeYDNJTehVTRoR6.jpg','test','test','test',4,'blade','lfoxy',4);
INSERT INTO `movie` VALUES (11,'Blade II', 'jlURNpXCMK830CsGRd939PJLh8c.jpg','test','test','test',2,'bladeii','lfoxy',4);
INSERT INTO `movie` VALUES (12,'Blade of the Imortal', 'bFaxg006Dt6J1k7qa7a5YuqbAhe.jpg','test','test','test',2,'bladeofhteimortal','lfoxy',4);
INSERT INTO `movie` VALUES (13,'Dragon Blade', '3gl11EsZS5vboQvvMYeCIzitaJz.jpg','test','test','test',1,'dragonblade','lfoxy',4);
INSERT INTO `movie` VALUES (14,'The Fate of the Furious', 'dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg','test','test','test',1,'fateofthefurious','lfoxy',4);
INSERT INTO `movie` VALUES (15,'Fast Food Nation', 's13uyUCCYs7zKj4MqsAPdK0lN4X.jpg','test','test','test',3,'fastfoodnation','lfoxy',4);
INSERT INTO `movie` VALUES (16,'Fast Times at Ridgemont High', '9y5rSeO0xH3m5oRJmhBusDkiS0j.jpg','test','test','test',3,'fasttimesatridgemonthigh','lfoxy',4);
INSERT INTO `movie` VALUES (17,'Bandits', '3wTzOr0CekiBJZL7ZiNE2y2H16N.jpg','test','test','test',3,'bandits','lfoxy',4);
INSERT INTO `movie` VALUES (18,'Bandidas', '6WnSdouYhXDowg9NrKY2fSV5o1W.jpg','test','test','test',3,'bandidas','lfoxy',4);
INSERT INTO `movie` VALUES (19,'B. Monkey', 'owKZAo5QxyulBwMvHqKn4a2abNc.jpg','test','test','test',3,'bmonkey','lfoxy',4);
INSERT INTO `movie` VALUES (20,'Band Aid', 'lcxx0vN0hhQi7KFpRaJlxAaLLhR.jpg','test','test','test',3,'bandaid','lfoxy',4);
INSERT INTO `movie` VALUES (21,'B', 'bvpfVMt0MRSXNXcycxOGiHQMevk.jpg','test','test','test',3,'b','lfoxy',4);
INSERT INTO `movie` VALUES (22,'The Back-Up Plan', '1Ig6ZQpLZfLsdvMLHD0inc2w0HB.jpg','test','test','test',3,'backupplan','lfoxy',4);
INSERT INTO `movie` VALUES (23,'B-Day', 'cDgrrQnCmC6kqUGaFZmK7DmsE7.jpg','test','test','test',3,'bday','lfoxy',4);
INSERT INTO `movie` VALUES (24,'Bandolero!', 'kmqy27Mk8zT0viBTZkqemkSZInQ.jpg','test','test','test',3,'bandolero','lfoxy',4);
INSERT INTO `movie` VALUES (25,'Be Afraid', 'ytkaL1wZcqgQKHLuU7Go3UxGpON.jpg','test','test','test',3,'beafraid','lfoxy',4);
INSERT INTO `movie` VALUES (26,'Be Cool', 'ekKCH7Zkb5ZTr1f1AczZY23FH.jpg','test','test','test',3,'becool','lfoxy',4);
INSERT INTO `movie` VALUES (27,'Be Somebody', 'igRnsNTGOLwnCIn0gnSnAQ95qx0.jpg','test','test','test',3,'besomebody','lfoxy',4);
INSERT INTO `movie` VALUES (28,'Be With You', 'sEeH8ce2YeZHFng3AddqsQ2niLf.jpg','test','test','test',3,'bewithyou','lfoxy',4);
INSERT INTO `movie` VALUES (29,'Be Kind Rewind', 'f0oX20YrQEiVPDH9InCQ1d3Cm66.jpg','test','test','test',3,'bekindrewind','lfoxy',4);
INSERT INTO `movie` VALUES (30,'Born To Be Blue', 'iEdh2CkSyDXBTAPlNS6uLF9yTTH.jpg','test','test','test',3,'borntobeblue','lfoxy',4);
INSERT INTO `movie` VALUES (31,'10', 'u8QzBwoCrCkXZUZr9pFTcRIVMxc.jpg','test','test','test',3,'10','lfoxy',4);
INSERT INTO `movie` VALUES (32,'Cars 2', 'AblhtULOVtrkSnFxRPQ8gBemxw9.jpg','test','test','test',3,'cars2','lfoxy',4);
INSERT INTO `movie` VALUES (33,'Iron Man 2', 'ArqpkNYGfcTIA6umWt6xihfIZZv.jpg','test','test','test',3,'ironman2','lfoxy',4);
INSERT INTO `movie` VALUES (34,'20,000 Leagues Under the Sea', 'yhoL2CxBp9IwMhHrCj6FIb2lrYR.jpg','test','test','test',3,'20000leaguesunderthesea','lfoxy',4);
INSERT INTO `movie` VALUES (35,'Blade Runner', 'p64TtbZGCElxQHpAMWmDHkWJlH2.jpg','test','test','test',3,'bladerunner','pwaite',6);
INSERT INTO `movie` VALUES (36,'Abyss', 'kRP5dGXDhKt7bDpXX4YBa4dRwlL.jpg','test','test','test',3,'abyss','pwaite',6);
INSERT INTO `movie` VALUES (37,'The Accountant', 'afhAUuWVB7k7PjJUd4lwO3rzhSq.jpg','test','test','test',4,'accountant','pwaite',6);
INSERT INTO `movie` VALUES (38,'Atomic Blonde', 'kV9R5h0Yct1kR8Hf8sJ1nX0Vz4x.jpg','test','test','test',3,'atomicblonde','pwaite',6);
INSERT INTO `movie` VALUES (39,'Ultimate Avengers', 'we6igIU5gXVwuSL6M6pJP75TwEf.jpg','test','test','test',3,'ultimateavengers','pwaite',6);
INSERT INTO `movie` VALUES (40,'After Earth', 'd0vReo0jcMhBjCLYZAFqWHcb7Lj.jpg','test','test','test',3,'afterearth','pwaite',6);
INSERT INTO `movie` VALUES (41,'Blade', 'r0RQ9ZOEZglLOeYDNJTehVTRoR6.jpg','test','test','test',4,'blade','pwaite',6);
INSERT INTO `movie` VALUES (42,'Blade of the Imortal', 'bFaxg006Dt6J1k7qa7a5YuqbAhe.jpg','test','test','test',2,'bladeofhteimortal','pwaite',6);
INSERT INTO `movie` VALUES (43,'Dragon Blade', '3gl11EsZS5vboQvvMYeCIzitaJz.jpg','test','test','test',1,'dragonblade','pwaite',6);
INSERT INTO `movie` VALUES (44,'The Fate of the Furious', 'dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg','test','test','test',1,'fateofthefurious','pwaite',6);
INSERT INTO `movie` VALUES (45,'Fast Food Nation', 's13uyUCCYs7zKj4MqsAPdK0lN4X.jpg','test','test','test',3,'fastfoodnation','pwaite',6);
INSERT INTO `movie` VALUES (46,'Fast Times at Ridgemont High', '9y5rSeO0xH3m5oRJmhBusDkiS0j.jpg','test','test','test',3,'fasttimesatridgemonthigh','pwaite',6);
INSERT INTO `movie` VALUES (47,'Bandits', '3wTzOr0CekiBJZL7ZiNE2y2H16N.jpg','test','test','test',3,'bandits','pwaite',6);
INSERT INTO `movie` VALUES (48,'Bandidas', '6WnSdouYhXDowg9NrKY2fSV5o1W.jpg','test','test','test',3,'bandidas','pwaite',6);
INSERT INTO `movie` VALUES (49,'B. Monkey', 'owKZAo5QxyulBwMvHqKn4a2abNc.jpg','test','test','test',3,'bmonkey','pwaite',6);
INSERT INTO `movie` VALUES (50,'Band Aid', 'lcxx0vN0hhQi7KFpRaJlxAaLLhR.jpg','test','test','test',3,'bandaid','pwaite',6);
INSERT INTO `movie` VALUES (51,'B', 'bvpfVMt0MRSXNXcycxOGiHQMevk.jpg','test','test','test',3,'b','pwaite',6);
INSERT INTO `movie` VALUES (52,'The Back-Up Plan', '1Ig6ZQpLZfLsdvMLHD0inc2w0HB.jpg','test','test','test',3,'backupplan','pwaite',6);
INSERT INTO `movie` VALUES (53,'B-Day', 'cDgrrQnCmC6kqUGaFZmK7DmsE7.jpg','test','test','test',3,'bday','pwaite',6);
INSERT INTO `movie` VALUES (54,'Bandolero!', 'kmqy27Mk8zT0viBTZkqemkSZInQ.jpg','test','test','test',3,'bandolero','pwaite',6);
INSERT INTO `movie` VALUES (55,'Be Afraid', 'ytkaL1wZcqgQKHLuU7Go3UxGpON.jpg','test','test','test',3,'beafraid','pwaite',6);
INSERT INTO `movie` VALUES (56,'Be Cool', 'ekKCH7Zkb5ZTr1f1AczZY23FH.jpg','test','test','test',3,'becool','pwaite',6);
INSERT INTO `movie` VALUES (57,'Be Somebody', 'igRnsNTGOLwnCIn0gnSnAQ95qx0.jpg','test','test','test',3,'besomebody','pwaite',6);
INSERT INTO `movie` VALUES (58,'Be With You', 'sEeH8ce2YeZHFng3AddqsQ2niLf.jpg','test','test','test',3,'bewithyou','pwaite',6);
INSERT INTO `movie` VALUES (59,'Be Kind Rewind', 'f0oX20YrQEiVPDH9InCQ1d3Cm66.jpg','test','test','test',3,'bekindrewind','pwaite',6);
INSERT INTO `movie` VALUES (60,'Born To Be Blue', 'iEdh2CkSyDXBTAPlNS6uLF9yTTH.jpg','test','test','test',3,'borntobeblue','pwaite',6);
INSERT INTO `movie` VALUES (61,'Cars 2', 'AblhtULOVtrkSnFxRPQ8gBemxw9.jpg','test','test','test',3,'cars2','pwaite',6);
INSERT INTO `movie` VALUES (62,'Iron Man 2', 'ArqpkNYGfcTIA6umWt6xihfIZZv.jpg','test','test','test',3,'ironman2','pwaite',6);
INSERT INTO `movie` VALUES (63,'20,000 Leagues Under the Sea', 'yhoL2CxBp9IwMhHrCj6FIb2lrYR.jpg','test','test','test',3,'20000leaguesunderthesea','pwaite',6);
INSERT INTO `movie` VALUES (64,'Blade II', 'jlURNpXCMK830CsGRd939PJLh8c.jpg','test','test','test',2,'bladeii','pwaite',6);
INSERT INTO `movie` VALUES (65,'Cy-Warrior', 'pNLQKmWBjpPfYUfTNvJGwsNLMFH.jpg','test','test','test',3,'cywarrior','pwaite',6);
INSERT INTO `movie` VALUES (66,'Cyborg', 'nOspcG8HP6KPdMvzezavRbzYCEw.jpg','test','test','test',4,'cyborg','pwaite',6);
INSERT INTO `movie` VALUES (67,'Cyrus', 'filMDJ2Ze7GjsCO2O4Pmwbw9kaO.jpg','test','test','test',2,'cyrus','pwaite',6);
INSERT INTO `movie` VALUES (68,'Cypher', 'qzLRviv0UUCbmbdBDQq8FdaWf2B.jpg','test','test','test',4,'cypher','pwaite',6);
INSERT INTO `movie` VALUES (69,'Mo', 'wwXUq5hCN6DsXVZJ6qc0RiQaGpc.jpg','test','test','test',3,'mo','pwaite',6);
INSERT INTO `movie` VALUES (70,'The Slow Mo Guys', 'jODHt7fJfUnUkT8pIvHgXNWRLn4.jpg','test','test','test',3,'slowmoguys','pwaite',6);
INSERT INTO `movie` VALUES (71,'Kung Ayaw Mo, Huwag Mo!', 'ed6zUcOdjyCQTosOg5m7DDF3zAJ.jpg','test','test','test',4,'kungayawmohuwagmo','pwaite',6);
INSERT INTO `movie` VALUES (72,'King Kong', 'iQYMVoI9QE2wQCOSrxhiBYd4v0w.jpg','test','test','test',5,'kingkong','pwaite',6);
INSERT INTO `movie` VALUES (73,'King Arthur', 'kKHayVkXaF3EZDx0ybkaWypJECJ.jpg','test','test','test',2,'kingarthur','pwaite',6);
INSERT INTO `movie` VALUES (74,'The Lion King', 'bKPtXn9n4M4s8vvZrbw40mYsefB.jpg','test','test','test',4,'lionking','pwaite',6);
INSERT INTO `movie` VALUES (75,'The Scorpion King', 'xHHMo8Za53XK8qpsdarrxUoxBwn.jpg','test','test','test',4,'scorpionking','pwaite',6);
INSERT INTO `movie` VALUES (76,'The King and I', 'jyAMSLdJymJ9xObCfZFXZFGFz8m.jpg','test','test','test',4,'kingandi','pwaite',6);
INSERT INTO `movie` VALUES (77,'Blood Diamond', 'wRamTzV6udKaMXrspxqOuo02zk0.jpg','test','test','test',5,'blooddiamond','pwaite',6);
INSERT INTO `movie` VALUES (78,'Diamonds Are Forever', 'viPjZ3JCOahcfNCcVhiPExusJoZ.jpg','test','test','test',3,'diamondsareforever','pwaite',6);
INSERT INTO `movie` VALUES (79,'21 Diamonds', 'pCOp9EAdJzRqJlhn7q82mIe6R1d.jpg','test','test','test',2,'21diamonds','pwaite',6);
INSERT INTO `movie` VALUES (80,'Feed The Fish', 'kbbI1GNNWibuWvk8Kf6p0dSapKr.jpg','test','test','test',5,'feedthefish','pwaite',6);
INSERT INTO `movie` VALUES (81,'21 Days', 'efZw0KolQKGsPxKSXQUZkc1LUhu.jpg','test','test','test',5,'21days','pwaite',6);
INSERT INTO `metadata_tmdb` VALUES (1, 'http://image.tmdb.org/t/p/', 'w92', 'w300');
INSERT INTO `role` VALUES (1,'admin','badadmin',1);
INSERT INTO `role` VALUES (2,'admin','jfourieadmin',2);
INSERT INTO `role` VALUES (3,'regular','jfourie',3);
INSERT INTO `role` VALUES (4,'regular','lfoxy',4);
INSERT INTO `role` VALUES (5,'regular','baduser',5);
INSERT INTO `role` VALUES (6,'regular','pwaite',6);
INSERT INTO `role` VALUES (7,'admin','pwaiteadmin',7);
